query {
  tasks {
    text
  }
}

{
  "data": {
    "tasks": [
      {
        "text": "Learn React"
      },
      {
        "text": "Learn GraphQL"
      },
      {
        "text": "Learn Prisma"
      }
    ]
  }
}